# Generated by Django 3.1.4 on 2020-12-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_title', models.CharField(max_length=50, verbose_name='Paper Title')),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Published Date')),
                ('authors', models.CharField(max_length=100, null=True, verbose_name='Authors')),
                ('paper_description', models.CharField(max_length=200, verbose_name='Report Description')),
                ('paper_category', models.CharField(choices=[('FinTech & Investing', 'fintech_investing'), ('Machine Learning', 'machine_learning'), ('Computational Biology', 'computational_biology'), ('Data Engineering', 'data_engineering')], max_length=50, verbose_name='Paper Category')),
                ('paper', models.FileField(upload_to='papers/', verbose_name='Paper PDF')),
            ],
            options={
                'verbose_name_plural': 'Papers',
                'ordering': ['-upload_date'],
            },
        ),
    ]
