# Generated by Django 3.1.3 on 2021-01-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201229_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='article_description',
            field=models.CharField(max_length=500, verbose_name='Article Description'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='article_slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='article_title',
            field=models.CharField(max_length=250, verbose_name='Article Titile'),
        ),
        migrations.AlterField(
            model_name='papermodel',
            name='authors',
            field=models.CharField(max_length=400, null=True, verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='papermodel',
            name='paper_description',
            field=models.CharField(max_length=500, verbose_name='Report Description'),
        ),
        migrations.AlterField(
            model_name='papermodel',
            name='paper_title',
            field=models.CharField(max_length=200, verbose_name='Paper Title'),
        ),
    ]
